version: "3"

services:
    proj_euler:
        build:
            context: .
        env_file:
            - ./.env
        ports:
            - 3000:3000
        networks:
            - proj_euler_network
    
    database:
        image: mongo:5.0
        volumes:
            - ./.data/database:/data/db
        networks:
            - proj_euler_network

networks:
    proj_euler_network:
