version: "3"

services:
    proj_euler:
        build:
            context: .
            dockerfile: dev.Dockerfile
        volumes:
            - ./__tests__:/app/__tests__
            - ./components:/app/components
            - ./dist:/app/dist
            - ./lib:/app/lib
            - ./pages:/app/pages
            - ./problems:/app/problems
            - ./public:/app/public
            - ./scripts:/app/scripts
            - ./styles:/app/styles
            - ./types:/app/types
            - ./jest.config.js:/app/jest.config.js
            - ./jest-mongodb-config.js:/app/jest-mongodb-config.js
            - ./next.config.js:/app/next.config.js
            - ./tsconfig.json:/app/tsconfig.json
        env_file:
            - ./.env
        ports:
            - 3000:3000
        networks:
            - proj_euler_network
    
    database:
        image: mongo:5.0
        volumes:
            - ./.data/database:/data/db
        ports:
            - 27017:27017
        networks:
            - proj_euler_network

networks:
    proj_euler_network:
