version: "3"

services:
    airetc:
        build:
            context: .
            dockerfile: dev.Dockerfile
        volumes:
            # TODO: Consolidate directories under a root dir
            - ./components:/app/components
            - ./dist:/app/dist
            - ./lib:/app/lib
            - ./pages:/app/pages
            - ./problems:/app/problems
            - ./public:/app/public
            - ./scripts:/app/scripts
            - ./styles:/app/styles
            - ./types:/app/types
        ports:
            - 3000:3000
        networks:
            - airetc_network
    
    database:
        image: mongo:5.0
        volumes:
            - ./.data/database:/data/db
        ports:
            - 27017:27017
        networks:
            - airetc_network

networks:
    airetc_network:
