version: "3"

services:
    airetc:
        build:
            context: .
        env_file:
            - ./.env
        ports:
            - 3000:3000
        networks:
            - airetc_network
    
    database:
        image: mongo:5.0
        volumes:
            - ./.data/database:/data/db
        ports:
            - 27017:27017
        networks:
            - airetc_network

networks:
    airetc_network:
